config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    # devise_for :users
    devise_for :users, controllers: {
      registrations: "users/registrations"
    }
    devise_scope :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    get "/home", to: "static_pages#home"
    get "/contact", to: "static_pages#contact"
    get "/about", to: "static_pages#about"
    get "/admin", to: "admin/admin_pages#index"
    get "/search", to: "searchs#index"
    get "/history-orders", to: "history_orders#index"

    resources :comments, only: %i(create destroy)
    resources :rates, only: %i(create destroy)
    resources :notifications, only: %i(index update)
    resources :orders, only: %i(new create show)
    resources :cart, only: %i(index create update)
    delete "cart_destroy", to: "cart#destroy"
    resources :users, only: %i(show)
    resources :requests
    resources :products, only: %i(index show)
    get "/shop", to: "products#index"
    resources :item_photos, only: :destroy
    namespace :admin do
      resources :categories, except: :show
      resources :products do
        collection do
          post :import
          get :export
        end
      end
      resources :orders, only: %i(index update)
      resources :requests, only: %i(index update destroy)
      resources :charts, only: %i(index)
      resources :users
      resources :schedules, only: %i(index create destroy)
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products_orders, dependent: :destroy
  has_many :products, through: :products_orders
  enum status: {pending: 0, processing: 1, completed: 2, canceled: 3}
  scope :by_created_at, ->{order created_at: :desc}

  validates :receiver_name, presence: true,
    length: {maximum: Settings.user.name.max_length}
  validates :receiver_phone, presence: true, numericality: true
  validates :receiver_address, presence: true
  validates :description, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :find_order, only: %i(update)

  authorize_resource

  def index
    @orders = Order.by_created_at.includes(:products_orders, :products)
                   .page(params[:page]).per Settings.products.per_page
  end

  def update
    return if @order.canceled? || @order.completed?
    case params[:status]
    when statuses(:processing)
      key = statuses :processing
    when statuses(:completed)
      key = statuses :completed
    when statuses(:canceled)
      key = statuses :canceled
    else
      flash[:danger] = t "helpers.error[update_order_fail]"
      redirect_to admin_orders_path
      return
    end
    action_status key
    redirect_when_success
  end

  private

  def find_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:danger] = t "helpers.error[order_not_found]"
    redirect_to admin_orders_path
  end

  def statuses status
    Order.statuses[status].to_s
  end

  def action_status key
    if key == statuses(:processing)
      @order.processing!
      create_notification Order.name, @order,
        "order.processing", @order.user
    elsif key == statuses(:completed)
      @order.completed!
      create_notification Order.name, @order,
        "order.completed", @order.user
    elsif key == statuses(:canceled)
      @order.canceled!
      create_notification Order.name, @order,
        "order.canceled", @order.user
    end
  rescue ArgumentError
    redirect_when_error
  end

  def redirect_when_success
    flash[:success] = t "helpers.success[updated_order]"
    redirect_to admin_orders_path
  end

  def redirect_when_error
    flash[:danger] = t "helpers.error[update_order_fail]"
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: :show

  authorize_resource

  def show; end

  def new
    products_in_cart = check_cookie_cart
    list_products_cart products_in_cart
    return @order = Order.new if @products.any?
    flash[:danger] = t "helpers.info[access_denied]"
    redirect_to cart_index_path
  end

  def create
    products_in_cart = check_cookie_cart
    list_products_cart products_in_cart
    @order = Order.new order_params.merge(user_id: current_user.id,
      status: :pending, total_price: get_subtotal_price(@products))
    Order.transaction do
      @order.save
      save_product_order @products
      flash[:info] = t "helpers.info[create-order]"
      redirect_to order_path(@order)
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = t "helpers.error[create-order-fail-save]"
    render :new
  end

  private

  def order_params
    params.require(:order).permit :receiver_name, :receiver_phone,
      :receiver_address, :description
  end

  def save_product_order products
    products.each do |p|
      @products_order = @order.products_orders.new(product_id: p.id,
        quantity: p.total_quantity, actual_price: p.price_discounted)
      @products_order.save
    end
    create_notification Order.name, @order,
      "order.create", User.admin.first
    cookies.delete :products
    # OrderMailer.order_complete(current_user, @order).deliver_now
  end

  def find_order
    @order = Order.find_by(id: params[:id])
    return if @order
    flash[:danger] = t "helpers.error[order_not_found]"
    redirect_to cart_path
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def css_with_status order
    case order.status
    when "pending"
      "info"
    when "processing"
      "warning"
    when "completed"
      "success"
    when "canceled"
      "danger"
    end
  end
end

app/views/admin/orders/_modal.html.erb
<div class="modal fade" id="modal-<%= modal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title" id="exampleModalLabel"><%= t ".detail_order" %><%= modal.id %></span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <section class="order_details">
          <div class="container">
            <div class="row order_d_inner">
              <div class="col-lg-6">
                <div class="details_item">
                  <h4><%= t ".order_info" %></h4>
                  <ul class="list">
                    <li><a href="#"><span><%= t ".order_id" %></span> : <%= modal.id %></a></li>
                    <li><a href="#"><span><%= t ".date" %></span> : <%= l modal.created_at, format: :short %></a></li>
                    <li><a href="#"><span><%= t ".subtotal" %></span> : <%= number_to_currency modal.total_price %></a></li>
                    <li><a href="#"><span><%= t ".status" %></span> : <%= modal.status %></a></li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="details_item">
                  <h4><%= t ".receiver_info" %></h4>
                  <ul class="list">
                    <li><a href="#"><span><%= t ".receiver_name" %></span> : <%= modal.receiver_name %></a></li>
                    <li><a href="#"><span><%= t ".receiver_phone" %></span> : <%= modal.receiver_phone %></a></li>
                    <li><a href="#"><span><%= t ".receiver_address" %></span> : <%= modal.receiver_address %></a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="row order_d_inner">
              <div class="col-lg-12">
                <h5><%= t ".description" %></h5>
                <span><%= modal.description %></span>
              </div>
            </div>
            <div class="order_details_table">
              <h2><%= t ".order_details" %></h2>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col"><%= t ".product" %></th>
                      <th scope="col"><%= t ".quantity" %></th>
                      <th scope="col"><%= t ".total" %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% modal.products_orders.each do |p| %>
                      <tr>
                        <td>
                          <p><%= p.product.name %></p>
                        </td>
                        <td>
                          <h5>
                            <%= p.quantity %>
                            <% if p.quantity > p.product_quantity %>
                            (<%= t ".not_enough" %>)
                            <% end %>
                          </h5>
                          <p>(<%= t ".in_stock" %><%= p.product_quantity %>)</p>
                        </td>
                        <td>
                          <p><%= number_to_currency total_price(p.quantity, p.actual_price) %></p>
                        </td>
                      </tr>
                    <% end %>
                    <tr>
                      <td>
                        <h4><%= t ".subtotal" %></h4>
                      </td>
                      <td></td>
                      <td>
                        <p><%= number_to_currency modal.total_price %></p>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <% unless modal.completed? || modal.canceled? %>
              <div class="row order_d_inner">
                <div class="col-lg-12">
                  <h5><%= t ".change_status" %></h5>
                  <%= form_tag admin_order_path(id: modal.id, status: Order.statuses[:pending]), method: :put, style: "display: inline;" do %>
                    <% if modal.pending? || modal.processing? %>
                      <%= button_tag type: :button, class: "genric-btn disable" do %>
                        <%= t ".pending" %>
                      <% end %>
                    <% else %>
                      <%= button_tag type: :submit, class: "genric-btn info" do %>
                        <%= t ".pending" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= form_tag admin_order_path(id: modal.id, status: Order.statuses[:processing]), method: :put, style: "display: inline;" do %>
                    <% if modal.processing? %>
                      <%= button_tag type: :button, class: "genric-btn disable" do %>
                        <%= t ".processing" %>
                      <% end %>
                    <% else %>
                      <%= button_tag type: :submit, class: "genric-btn warning" do %>
                        <%= t ".processing" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= form_tag admin_order_path(id: modal.id, status: Order.statuses[:completed]), method: :put, style: "display: inline;" do %>
                    <%= button_tag type: :submit, class: "genric-btn success" do %>
                      <%= t ".completed" %>
                    <% end %>
                  <% end %>
                  <%= form_tag admin_order_path(id: modal.id, status: Order.statuses[:canceled]), method: :put, style: "display: inline;" do %>
                    <%= button_tag type: :submit, class: "genric-btn danger" do %>
                      <%= t ".canceled" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </section>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= counter_index order_counter %></td>
  <td><%= order.user.name %></td>
  <td><%= order.receiver_name %></td>
  <td><%= order.receiver_phone %></td>
  <td><%= order.receiver_address %></td>
  <td><%= l order.created_at, format: :short %></td>
  <td><%= l order.updated_at, format: :short %></td>
  <td><%= number_to_currency order.total_price %></td>
  <td>
    <button type="button" class="genric-btn <%= css_with_status order %>"><%= order.status %></button>
  </td>
  <td>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-<%= order.id %>">
      <%= t ".detail" %>
    </button>
  </td>
</tr>

app/views/admin/orders/index.html.erb
<% provide :title, t(".title") %>
<section class="section_gap_bottom">
  <div class="main-content">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
      <ul class="breadcrumb">
        <li>
          <i class="ace-icon fa fa-home home-icon"></i>
          <%= link_to t(".home"), admin_path %>
        </li>
        <li class="active">
          <i class="fas fa-angle-right"></i>
          <%= t ".title" %>
        </li>
      </ul>
      <!-- /.breadcrumb -->
    </div>
    <div class="main-content-inner container">
      <div class="page-content">
        <div class="row">
          <div class="col-xs-12">
            <div>
              <% if @orders.any? %>
                <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th><%= t ".id" %></th>
                      <th><%= t ".orderer" %></th>
                      <th><%= t ".receiver_name" %></th>
                      <th><%= t ".receiver_phone" %></th>
                      <th><%= t ".receiver_address" %></th>
                      <th><%= t ".created_at" %></th>
                      <th><%= t ".updated_at" %></th>
                      <th><%= t ".total_price" %></th>
                      <th><%= t ".status" %></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @orders %>
                  </tbody>
                </table>
              <% else %>
                <%= t ".no_order" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- /.page-content -->
      <%= paginate @orders %>
    </div>
  </div>
  <%= render partial: "admin/orders/modal", collection: @orders %>
  <!-- /.main-content -->
</section>