config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    # devise_for :users
    devise_for :users, controllers: {
      registrations: "users/registrations"
    }
    devise_scope :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    get "/home", to: "static_pages#home"
    get "/contact", to: "static_pages#contact"
    get "/about", to: "static_pages#about"
    get "/admin", to: "admin/admin_pages#index"
    get "/search", to: "searchs#index"
    get "/history-orders", to: "history_orders#index"

    resources :comments, only: %i(create destroy)
    resources :rates, only: %i(create destroy)
    resources :notifications, only: %i(index update)
    resources :orders, only: %i(new create show)
    resources :cart, only: %i(index create update)
    delete "cart_destroy", to: "cart#destroy"
    resources :users, only: %i(show)
    resources :requests
    resources :products, only: %i(index show)
    get "/shop", to: "products#index"
    resources :item_photos, only: :destroy
    namespace :admin do
      resources :categories, except: :show
      resources :products do
        collection do
          post :import
          get :export
        end
      end
      resources :orders, only: %i(index update)
      resources :requests, only: %i(index update destroy)
      resources :charts, only: %i(index)
      resources :users
      resources :schedules, only: %i(index create destroy)
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include SearchCop
  require "csv"

  belongs_to :category
  belongs_to :user
  has_many :history_views, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :products_orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :item_photos, dependent: :destroy
  has_many :product_schedules, dependent: :destroy

  delegate :name, to: :category, prefix: true

  accepts_nested_attributes_for :item_photos, allow_destroy: true,
    reject_if: proc{|attributes| attributes["photo"].blank?}

  validates :name, presence: true,
    length: {maximum: Settings.products.name_length}
  validates :description, presence: true
  validates :price, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero}
  validates :quantity, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   only_integer: true}
  validates :rating, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   less_than_or_equal_to: Settings.products.max_rating}
  validates :views, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   only_integer: true}
  validates :discount, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   less_than_or_equal_to: Settings.products.max_discount}

  validates :category_id, presence: true

  scope :by_updated_at, ->{order updated_at: :desc}
  scope :find_product_id, ->(id){where id: id}
  scope :lasted, ->{order created_at: :desc}
  scope :high_discount, ->{order discount: :desc}
  search_scope :search_product_public do
    attributes all: [:name, :description]
    options :all, type: :fulltext
    attributes category: "category.name"
    options :category, type: :fulltext
  end
  scope :activated, ->{where activated: true}
  scope :not_yet_activate, ->{where activated: false}
  scope :select_price_discounted,
    ->{select("products.*", "price*(100-discount) as price_discounted")}

  scope :sort_product, (lambda do |sort_option|
    case sort_option
    when "sort_a_z"
      order(name: :asc)
    when "sort_z_a"
      order(name: :desc)
    when "sort_new"
      order(created_at: :desc)
    when "sort_price_a_z"
      order(price_discounted: :desc)
    when "sort_price_z_a"
      order(price_discounted: :asc)
    end
  end)
  scope :rating, (lambda do |rating_option|
    return if rating_option.nil?
    where("rating > ?", rating_option)
  end)
  scope :price_min, (lambda do |price_min|
    return if price_min.nil?
    where("price > ?", price_min)
  end)
  scope :price_max, (lambda do |price_max|
    return if price_max.nil?
    where("price < ?", price_max)
  end)
  scope :by_category_id, (lambda do |category_id|
    return if category_id.nil?
    category = Category.sub_categories_or(category_id)
    where category_id: category if category.any?
  end)
  scope :by_hot_trend, (lambda do |hot_trend|
    case hot_trend
    when "hot-trend"
      order(views: :desc)
    when "new-products"
      order(id: :desc)
    when "sale-off"
      order(discount: :desc)
    when "high-rating"
      order(rating: :desc)
    end
  end)

  attr_accessor :total_quantity, :price_discounted

  def get_total_price
    return price_discounted * total_quantity if total_quantity.present?
    price_discounted
  end

  class << self
    def import_file file, overwrite, current_user
      init file, current_user
      import! @header, @products if @products.any?
      if @products_update.any? && overwrite.present?
        Product.import! @header, @products_update,
          on_duplicate_key_update: [:name, :price, :quantity, :category_id]
      end
      {
        counter_create: @counter_create,
        counter_update: @counter_update,
        counter_wrong_category: @counter_wrong_category
      }
    end

    def open_spreadsheet file
      case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

    def find_category name
      category = Category.find_by name: name
      return category.id if category
      false
    end

    def find_product id
      @product = Product.activated.find_by id: id
      return true if @product
      false
    end

    def init file, current_user
      spreadsheet = open_spreadsheet(file)
      @header = spreadsheet.row(1)
      @header[4] = "category_id"
      @header << "user_id"
      @products = []
      @products_update = []
      read_file spreadsheet, current_user
    end

    def read_file spreadsheet, current_user
      @counter_create = 0
      @counter_update = 0
      @counter_wrong_category = 0
      (2..spreadsheet.last_row).each do |i|
        @row = spreadsheet.row(i)
        category_id = find_category(@row[4])
        unless category_id
          @counter_wrong_category += 1
          next
        end
        @row[4] = category_id
        if find_product(@row[0])
          found_product
          @counter_update += 1
        else
          not_found_product current_user
          @counter_create += 1
        end
      end
    end

    def found_product
      @row << @product.user_id
      @products_update << @row
    end

    def not_found_product current_user
      @row << current_user.id
      @products << @row
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable
  has_many :history_views, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :viewed_products, through: :history_views, source: :product
  enum role: {customer: 0, admin: 1}
  mount_uploader :avatar, PictureUploader

  validates :name, presence: true,
    length: {maximum: Settings.user.name.max_length}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    length: {maximum: Settings.user.email.max_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  # has_secure_password
  # validates :password, presence: true,
  #   length: {minimum: Settings.user.password.min_length},

  before_save :downcase_email
  scope :by_name, ->{order(name: :asc)}

  attr_accessor :skip_password_validation

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, except: %i(new create index import)
  before_action :sub_cat, except: %i(show destroy)

  authorize_resource

  def index
    list_product
    respond_to do |format|
      format.html
      format.xls{send_data Product.to_csv, filename: "product.xls"}
      format.csv do
        if params[:template].present?
          send_data Product.to_csv_template, filename: "template.csv"
        else
          send_data Product.to_csv, filename: "product.csv"
        end
      end
    end
  end

  def new
    @admin_product = Product.new
    @picture = @admin_product.item_photos.build
  end

  def create
    @admin_product = Product.new product_params
    @admin_product.user_id = current_user.id
    Product.transaction do
      @admin_product.save!
      params[:item_photos]["photo"].each do |a|
        @picture = @admin_product.item_photos.create!(photo: a)
      end
      flash[:info] = t "helpers.success[added_product]"
      redirect_to admin_products_path
    end
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def edit
    photos = @admin_product.item_photos
    return if photos.any?
    @picture = photos.build
  end

  def update
    Product.transaction do
      @admin_product.update_attributes! product_params
      if params[:item_photos].present?
        params[:item_photos]["photo"].each do |a|
          @picture = @admin_product.item_photos.create!(photo: a)
        end
      end
      flash[:success] = t "helpers.success[update_product]"
      redirect_to admin_products_path
    end
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    if @admin_product.destroy
      flash[:success] = t "helpers.success[deleted_product]"
    else
      flash[:danger] = t "helpers.error[delete_failed]"
    end
    redirect_to admin_products_path
  end

  def import
    if params[:file].present?
      counter = Product.import_file params[:file],
        params[:overwrite], current_user
      render_flash counter
      flash[:success] = t("helpers.success[product_create]",
        counter: counter[:counter_create])
    else
      flash[:danger] = t("helpers.error[product_import]")
    end
    redirect_to admin_products_path
  end

  def export
    @admin_products = Product.order(category_id: :desc)
    respond_to do |format|
      format.xlsx
      format.pdf do
        render pdf: "products",
          layout: "pdf.html",
          template: "admin/products/products.pdf.html.erb",
          footer: {right: "[page]"},
          margin: {top: Settings.margin_layout.top,
                   bottom: Settings.margin_layout.bot,
                   left: Settings.margin_layout.left,
                   right: Settings.margin_layout.right},
          orientation: "Portrait", page_size: "A4"
      end
    end
  end

  private

  def product_params
    params.require(:product).permit :name, :category_id,
      :price, :discount, :quantity, :description,
      item_photos_attributes: [:id, :photo]
  end

  def find_product
    @admin_product = Product.activated.find_by id: params[:id]
    return if @admin_product
    flash[:danger] = t "helpers.error[product_not_found]"
    redirect_to admin_products_path
  end

  def sub_cat
    @sub_categories = Category.sub_only.by_name
  end

  def list_product
    @search = Product.activated.search(params[:q])
    @products = @search.result.page(params[:page])
      .per Settings.products.per_page
  end

  def render_flash counter
    if params[:overwrite].present?
      flash[:info] = t("helpers.success[product_update]",
        counter: counter[:counter_update])
    else
      flash[:warning] = t("helpers.success[product_update_ignore]",
        counter: counter[:counter_update])
    end
    flash[:danger] = t("helpers.success[product_wrong_category]",
      counter: counter[:counter_wrong_category])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  before_action :load_categories
  before_action :find_product, only: :show

  def index
    shop_parmas = params.slice(:rating,
      :price_min, :price_max, :sort, :shop, :cat)
    if shop_parmas.blank?
      @products = Product.activated.by_updated_at
    elsif params[:shop].present?
      @products = Product.activated.by_hot_trend(params[:shop])
    else
      filter
    end
    @products = @products.page(params[:page]).per Settings.products.per_page
  end

  def show
    new_history_view
    @product.update_attribute :views, @product.views + Settings.products.views
    @comments = Comment.product_comments_parrent(params[:id]).by_date
    @reviews = Rate.product_reviews(params[:id]).by_date
  end

  private

  def find_product
    @product = Product.activated.find_by id: params[:id]
    return if @product
    flash[:danger] = t "helpers.error[product_not_found]"
    redirect_to shop_path
  end

  def filter
    @products = Product.select_price_discounted
                       .rating(params[:rating])
                       .price_min(params[:price_min])
                       .price_max(params[:price_max])
                       .by_category_id(params[:cat])
                       .sort_product(params[:sort])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def overall product
    @overall = product.rates.average(:rating)
    @overall = 0 if @overall.blank?
  end

  def new_history_view
    return unless user_signed_in?
    check_history_view_product @product.id
    check_history_view_quatity
    @history_view = HistoryView.new user_id: current_user.id,
      product_id: @product.id
    @history_view.save
  end

  def check_history_view_quatity
    length = current_user.history_views.length
    length_request = Settings.products.history_view
    current_user.history_views.first.destroy if length == length_request
  end

  def check_history_view_product product_id
    current_user.history_views.each do |h|
      h.destroy if h.product_id == product_id
    end
  end
end

app/views/admin/products/_form.html.erb
<%= render "shared/error_messages", object: f.object %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.fields_for :item_photos do |p| %>
    <%= f.label :picture %> <br>
    <%= p.file_field :photo, multiple: true, name: "item_photos[photo][]", class: "upload-image", accept: Settings.accept_image %> <br>
  <% end %>
  <div id="preview"></div>
</div>
<div class="form-group">
  <%= f.label :category %>
  <%= f.collection_select :category_id, @sub_categories, :id, :name, include_blank: false, class: "form-control"%>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :discount %>
  <%= f.number_field :discount, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :quantity %>
  <%= f.number_field :quantity, min: 0, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: "10" %>
</div>
<%= f.submit yield(:button_text), class: "btn btn-primary" %>

app/views/admin/products/_modal.html.erb
<div class="modal fade" id="modal-scheduler" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title" id="exampleModalLabel"><%= t ".scheduler_title" %></span>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <section class="order_details">
          <div class="container">
            <div class="row order_d_inner">
                <%= form_for(Schedule.new, url: admin_schedules_path) do |f| %>
                  <%= render "shared/error_messages", object: f.object %>
                  <%= f.label :name %>
                  <%= f.text_field :name, class: "form-control" %>
                  <%= f.label :start_time %>
                  <%= f.datetime_local_field :start_time, min: Time.now, class: "form-control" %>
                  <%= f.label :end_time %>
                  <%= f.datetime_local_field :end_time, min: Time.now, class: "form-control" %>
                  <%= f.label :discount %>
                  <%= f.number_field :discount, min: 0, max: 100, class: "form-control" %>
                  <%= f.label :product %>
                  <%= hidden_field_tag :product_ids, "" %>
                  <div id="product_in_schedule"></div>
                  <%= f.submit t(".add"), class: "btn btn-primary submit-schedule" %>
                <% end %>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_product.html.erb
<tr>
  <td><input type="checkbox" class="checkbox" value="<%= product.id %>" name="<%= product.name %>"></td>
  <td><%= product_counter + 1 %></td>
  <td><%= link_to product.name, product, target: "_blank"%></td>
  <% if product.item_photos.first %>
    <% photo_url = product.item_photos.first.photo_url %>
  <% else %>
    <% photo_url = "/assets/fallback/default.jpg" %>
  <% end %>
  <td><%= image_tag photo_url, class: "table-img" %></td>
  <td><%= number_to_currency(product.price) %></td>
  <td><%= product.quantity %></td>
  <td><%= product.discount %></td>
  <td><%= product.category.name %></td>
  <td><%= l product.created_at %></td>
  <td><%= l product.updated_at %></td>
  <td>
    <%= link_to edit_admin_product_path(product) do %>
      <span class="far fa-edit"></span> <%= t ".edit" %>
    <% end %>
    <%= link_to(admin_product_path(product), method: :delete, data: { confirm: t(".confirm") }) do %>
      <span class="far fa-trash-alt"></span> <%= t ".delete" %>
    <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".edit") %>
<section class="section_gap_bottom container">
  <div class="main-content">
    <div class="main-content-inner">
      <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
          <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <%= link_to t(".home"), admin_path %>
          </li>
          <li>
            <i class="fas fa-angle-right"></i>
            <%= link_to t(".products"), admin_products_path %>
          </li>
          <li class="active">
            <i class="fas fa-angle-right"></i>
            <%= t ".title" %>
          </li>
        </ul>
        <!-- /.breadcrumb -->
      </div>
      <div class="page-content">
        <div class="page-header">
          <h1><%= t ".title" %></h1>
          <hr>
        </div>
        <!-- /.page-header -->
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div class="col-lg-10 col-md-6 col-md-offset-3">
                <% @admin_product.item_photos.each do |p| %>
                  <% if p.id.present? %>
                    <%= image_tag p.photo_url, class: "p_image" %>
                    <%= link_to t(".destroy"), item_photo_path(p), method: :delete %>
                  <% end %>
                <% end %>
                <%= form_for [:admin, @admin_product], html: {multipart: true}, url: {action: :update, id: @admin_product.id} do |f| %>
                  <%= render partial: "form", locals: { f: f } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.page-content -->
    </div>
  </div>
  <!-- /.main-content -->
</section>

app/views/admin/products/index.html.erb
<% provide :title, t(".title") %>
<section class="section_gap_bottom">
  <div class="main-content">
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
      <ul class="breadcrumb">
        <li>
          <i class="ace-icon fa fa-home home-icon"></i>
          <%= link_to t(".home"), admin_path %>
        </li>
        <li class="active">
          <i class="fas fa-angle-right"></i>
          <%= t ".title" %>
        </li>
      </ul>
      <!-- /.breadcrumb -->
    </div>
    <div class="main-content-inner container">
      <div class="page-content">
        <div class="page-header">
          <h1><%= t ".title" %></h1>
          <hr>
        </div>
        <!-- /.page-header -->
        <div class="row">
          <div class="col-sm-12">
            <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
              <div class="form-group">
                <%= f.collection_select :category_id_eq, @sub_categories, :id, :name, {prompt: true}, {class: "form-control"} %>
                <%= f.text_field :name_cont, placeholder: t(".name"), class: "form-control" %>
              </div>
              <%= f.submit t(".search"), class: "btn btn-infoear" %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12">
            <h5>
              <%= form_tag import_admin_products_path, multipart: true, class: "md-form" do %>
                <div class="form-group">
                  <%= file_field_tag :file, class: "form-control-file" %>
                </div>
                <%= submit_tag t(".import"), class: "btn-success" %>
                <%= check_box_tag :overwrite %>
                <%= label_tag :overwrite, t(".overwrite") %>
              <% end %>
            </h5>
            <h5>
              <%= link_to(new_admin_product_path) do %>
                <span class="fas fa-plus-square"><%= t ".new" %></span>
              <% end %>
              <%= link_to export_admin_products_path(format: :xlsx), class: "excel" do %>
                <i class="fas fa-file-excel" aria-hidden="true"></i> <%= t ".export_excel" %>
              <% end %>
              <%= link_to export_admin_products_path(format: :pdf), class: "pdf" do %>
                <i class="fas fa-file-pdf" aria-hidden="true"></i> <%= t ".export_pdf" %>
              <% end %>
              <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-scheduler" id="schedule">
                <%= t ".scheduler" %>
              </button>
            </h5>
            <!-- div.dataTables_borderWrap -->
            <div>
              <% if @products.any? %>
                <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th><input type="checkbox" id="checkAll" name="checkAll"></th>
                      <th>ID</th>
                      <th><%= sort_link(@search, :name, t(".name")) %></th>
                      <th><%= t ".picture" %></th>
                      <th><%= sort_link(@search, :price, t(".price")) %></th>
                      <th><%= sort_link(@search, :quantity, t(".quantity")) %></th>
                      <th><%= sort_link(@search, :discount, t(".discount")) %></th>
                      <th><%= sort_link(@search, :category, t(".category")) %></th>
                      <th><%= sort_link(@search, :created_at, t(".created_at")) %></th>
                      <th><%= sort_link(@search, :updated_at, t(".updated_at")) %></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render @products %>
                  </tbody>
                </table>
              <% else %>
                <%= ".no_data" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- /.page-content -->
      <%= paginate @products %>
    </div>
  </div>
  <%= render "admin/products/modal" %>
  <!-- /.main-content -->
</section>
<%= javascript_include_tag "checkbox" %>

app/views/admin/products/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".add") %>
<section class="section_gap_bottom container">
  <div class="main-content">
    <div class="main-content-inner">
      <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
          <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <%= link_to t(".home"), admin_path %>
          </li>
          <li>
            <i class="fas fa-angle-right"></i>
            <%= link_to t(".products"), admin_products_path %>
          </li>
          <li class="active">
            <i class="fas fa-angle-right"></i>
            <%= t ".title" %>
          </li>
        </ul>
        <!-- /.breadcrumb -->
      </div>
      <div class="page-content">
        <div class="page-header">
          <h1><%= t ".title" %></h1>
          <hr>
        </div>
        <!-- /.page-header -->
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div class="col-lg-10 col-md-6 col-md-offset-3">
                <%= form_for [:admin, @admin_product], html: {multipart: true}, url: {action: :create, id: @admin_product.id} do |f| %>
                  <%= render partial: "form", locals: { f: f } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.page-content -->
    </div>
  </div>
  <!-- /.main-content -->
</section>

app/views/admin/products/products.pdf.html.erb
<div class="container">
  <h1><%= t ".list_products" %></h1>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>ID</th>
        <th><%= t ".name" %></th>
        <th><%= t ".category" %></th>
        <th><%= t ".price" %></th>
        <th><%= t ".quantity" %></th>
        <th><%= t ".created_at" %></th>
      </tr>
    </thead>
    <tbody>
      <% @admin_products.each_with_index do |product, index| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.name %></td>
          <td><%= product.category.name %></td>
          <td><%= product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= l product.created_at, format: :short %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>