config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    # devise_for :users
    devise_for :users, controllers: {
      registrations: "users/registrations"
    }
    devise_scope :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    get "/home", to: "static_pages#home"
    get "/contact", to: "static_pages#contact"
    get "/about", to: "static_pages#about"
    get "/admin", to: "admin/admin_pages#index"
    get "/search", to: "searchs#index"
    get "/history-orders", to: "history_orders#index"

    resources :comments, only: %i(create destroy)
    resources :rates, only: %i(create destroy)
    resources :notifications, only: %i(index update)
    resources :orders, only: %i(new create show)
    resources :cart, only: %i(index create update)
    delete "cart_destroy", to: "cart#destroy"
    resources :users, only: %i(show)
    resources :requests
    resources :products, only: %i(index show)
    get "/shop", to: "products#index"
    resources :item_photos, only: :destroy
    namespace :admin do
      resources :categories, except: :show
      resources :products do
        collection do
          post :import
          get :export
        end
      end
      resources :orders, only: %i(index update)
      resources :requests, only: %i(index update destroy)
      resources :charts, only: %i(index)
      resources :users
      resources :schedules, only: %i(index create destroy)
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include SearchCop
  require "csv"

  belongs_to :category
  belongs_to :user
  has_many :history_views, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :products_orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :item_photos, dependent: :destroy
  has_many :product_schedules, dependent: :destroy

  delegate :name, to: :category, prefix: true

  accepts_nested_attributes_for :item_photos, allow_destroy: true,
    reject_if: proc{|attributes| attributes["photo"].blank?}

  validates :name, presence: true,
    length: {maximum: Settings.products.name_length}
  validates :description, presence: true
  validates :price, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero}
  validates :quantity, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   only_integer: true}
  validates :rating, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   less_than_or_equal_to: Settings.products.max_rating}
  validates :views, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   only_integer: true}
  validates :discount, presence: true,
    numericality: {greater_than_or_equal_to: Settings.products.zero,
                   less_than_or_equal_to: Settings.products.max_discount}

  validates :category_id, presence: true

  scope :by_updated_at, ->{order updated_at: :desc}
  scope :find_product_id, ->(id){where id: id}
  scope :lasted, ->{order created_at: :desc}
  scope :high_discount, ->{order discount: :desc}
  search_scope :search_product_public do
    attributes all: [:name, :description]
    options :all, type: :fulltext
    attributes category: "category.name"
    options :category, type: :fulltext
  end
  scope :activated, ->{where activated: true}
  scope :not_yet_activate, ->{where activated: false}
  scope :select_price_discounted,
    ->{select("products.*", "price*(100-discount) as price_discounted")}

  scope :sort_product, (lambda do |sort_option|
    case sort_option
    when "sort_a_z"
      order(name: :asc)
    when "sort_z_a"
      order(name: :desc)
    when "sort_new"
      order(created_at: :desc)
    when "sort_price_a_z"
      order(price_discounted: :desc)
    when "sort_price_z_a"
      order(price_discounted: :asc)
    end
  end)
  scope :rating, (lambda do |rating_option|
    return if rating_option.nil?
    where("rating > ?", rating_option)
  end)
  scope :price_min, (lambda do |price_min|
    return if price_min.nil?
    where("price > ?", price_min)
  end)
  scope :price_max, (lambda do |price_max|
    return if price_max.nil?
    where("price < ?", price_max)
  end)
  scope :by_category_id, (lambda do |category_id|
    return if category_id.nil?
    category = Category.sub_categories_or(category_id)
    where category_id: category if category.any?
  end)
  scope :by_hot_trend, (lambda do |hot_trend|
    case hot_trend
    when "hot-trend"
      order(views: :desc)
    when "new-products"
      order(id: :desc)
    when "sale-off"
      order(discount: :desc)
    when "high-rating"
      order(rating: :desc)
    end
  end)

  attr_accessor :total_quantity, :price_discounted

  def get_total_price
    return price_discounted * total_quantity if total_quantity.present?
    price_discounted
  end

  class << self
    def import_file file, overwrite, current_user
      init file, current_user
      import! @header, @products if @products.any?
      if @products_update.any? && overwrite.present?
        Product.import! @header, @products_update,
          on_duplicate_key_update: [:name, :price, :quantity, :category_id]
      end
      {
        counter_create: @counter_create,
        counter_update: @counter_update,
        counter_wrong_category: @counter_wrong_category
      }
    end

    def open_spreadsheet file
      case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

    def find_category name
      category = Category.find_by name: name
      return category.id if category
      false
    end

    def find_product id
      @product = Product.activated.find_by id: id
      return true if @product
      false
    end

    def init file, current_user
      spreadsheet = open_spreadsheet(file)
      @header = spreadsheet.row(1)
      @header[4] = "category_id"
      @header << "user_id"
      @products = []
      @products_update = []
      read_file spreadsheet, current_user
    end

    def read_file spreadsheet, current_user
      @counter_create = 0
      @counter_update = 0
      @counter_wrong_category = 0
      (2..spreadsheet.last_row).each do |i|
        @row = spreadsheet.row(i)
        category_id = find_category(@row[4])
        unless category_id
          @counter_wrong_category += 1
          next
        end
        @row[4] = category_id
        if find_product(@row[0])
          found_product
          @counter_update += 1
        else
          not_found_product current_user
          @counter_create += 1
        end
      end
    end

    def found_product
      @row << @product.user_id
      @products_update << @row
    end

    def not_found_product current_user
      @row << current_user.id
      @products << @row
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, except: %i(new create index import)
  before_action :sub_cat, except: %i(show destroy)

  authorize_resource

  def index
    list_product
    respond_to do |format|
      format.html
      format.xls{send_data Product.to_csv, filename: "product.xls"}
      format.csv do
        if params[:template].present?
          send_data Product.to_csv_template, filename: "template.csv"
        else
          send_data Product.to_csv, filename: "product.csv"
        end
      end
    end
  end

  def new
    @admin_product = Product.new
    @picture = @admin_product.item_photos.build
  end

  def create
    @admin_product = Product.new product_params
    @admin_product.user_id = current_user.id
    Product.transaction do
      @admin_product.save!
      params[:item_photos]["photo"].each do |a|
        @picture = @admin_product.item_photos.create!(photo: a)
      end
      flash[:info] = t "helpers.success[added_product]"
      redirect_to admin_products_path
    end
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def edit
    photos = @admin_product.item_photos
    return if photos.any?
    @picture = photos.build
  end

  def update
    Product.transaction do
      @admin_product.update_attributes! product_params
      if params[:item_photos].present?
        params[:item_photos]["photo"].each do |a|
          @picture = @admin_product.item_photos.create!(photo: a)
        end
      end
      flash[:success] = t "helpers.success[update_product]"
      redirect_to admin_products_path
    end
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    if @admin_product.destroy
      flash[:success] = t "helpers.success[deleted_product]"
    else
      flash[:danger] = t "helpers.error[delete_failed]"
    end
    redirect_to admin_products_path
  end

  def import
    if params[:file].present?
      counter = Product.import_file params[:file],
        params[:overwrite], current_user
      render_flash counter
      flash[:success] = t("helpers.success[product_create]",
        counter: counter[:counter_create])
    else
      flash[:danger] = t("helpers.error[product_import]")
    end
    redirect_to admin_products_path
  end

  def export
    @admin_products = Product.order(category_id: :desc)
    respond_to do |format|
      format.xlsx
      format.pdf do
        render pdf: "products",
          layout: "pdf.html",
          template: "admin/products/products.pdf.html.erb",
          footer: {right: "[page]"},
          margin: {top: Settings.margin_layout.top,
                   bottom: Settings.margin_layout.bot,
                   left: Settings.margin_layout.left,
                   right: Settings.margin_layout.right},
          orientation: "Portrait", page_size: "A4"
      end
    end
  end

  private

  def product_params
    params.require(:product).permit :name, :category_id,
      :price, :discount, :quantity, :description,
      item_photos_attributes: [:id, :photo]
  end

  def find_product
    @admin_product = Product.activated.find_by id: params[:id]
    return if @admin_product
    flash[:danger] = t "helpers.error[product_not_found]"
    redirect_to admin_products_path
  end

  def sub_cat
    @sub_categories = Category.sub_only.by_name
  end

  def list_product
    @search = Product.activated.search(params[:q])
    @products = @search.result.page(params[:page])
      .per Settings.products.per_page
  end

  def render_flash counter
    if params[:overwrite].present?
      flash[:info] = t("helpers.success[product_update]",
        counter: counter[:counter_update])
    else
      flash[:warning] = t("helpers.success[product_update_ignore]",
        counter: counter[:counter_update])
    end
    flash[:danger] = t("helpers.success[product_wrong_category]",
      counter: counter[:counter_wrong_category])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  before_action :load_categories
  before_action :find_product, only: :show

  def index
    shop_parmas = params.slice(:rating,
      :price_min, :price_max, :sort, :shop, :cat)
    if shop_parmas.blank?
      @products = Product.activated.by_updated_at
    elsif params[:shop].present?
      @products = Product.activated.by_hot_trend(params[:shop])
    else
      filter
    end
    @products = @products.page(params[:page]).per Settings.products.per_page
  end

  def show
    new_history_view
    @product.update_attribute :views, @product.views + Settings.products.views
    @comments = Comment.product_comments_parrent(params[:id]).by_date
    @reviews = Rate.product_reviews(params[:id]).by_date
  end

  private

  def find_product
    @product = Product.activated.find_by id: params[:id]
    return if @product
    flash[:danger] = t "helpers.error[product_not_found]"
    redirect_to shop_path
  end

  def filter
    @products = Product.select_price_discounted
                       .rating(params[:rating])
                       .price_min(params[:price_min])
                       .price_max(params[:price_max])
                       .by_category_id(params[:cat])
                       .sort_product(params[:sort])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def overall product
    @overall = product.rates.average(:rating)
    @overall = 0 if @overall.blank?
  end

  def new_history_view
    return unless user_signed_in?
    check_history_view_product @product.id
    check_history_view_quatity
    @history_view = HistoryView.new user_id: current_user.id,
      product_id: @product.id
    @history_view.save
  end

  def check_history_view_quatity
    length = current_user.history_views.length
    length_request = Settings.products.history_view
    current_user.history_views.first.destroy if length == length_request
  end

  def check_history_view_product product_id
    current_user.history_views.each do |h|
      h.destroy if h.product_id == product_id
    end
  end
end

app/views/products/_comment.html.erb
<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
  <div class="row">
    <div class="col-lg-6">
      <% if @comments.any? %>
        <div class="comment_list">
          <% @comments.each do |comment| %>
            <% if comment.parent_id.nil? %>
              <div class="comment_item">
                <div class="media">
                  <div class="d-flex">
                    <%= image_tag comment.user.avatar.url %>
                  </div>
                  <div class="media-body">
                    <h4><%= comment.user.name %></h4>
                    <h5><%= l comment.updated_at, format: :short %></h5>
                    <% if comment.user.id == current_user.id %>
                      <%= link_to t(".delete"), "javascript:void(0)", class: "delete_btn",
                        data_id: comment.id, pid: @product.id %>
                    <% end %>
                    <a class="reply_btn" parent_id="<%= comment.id %>"
                      user="<%= comment.user.name %>" href="javascript:void(0)"><%= t ".reply" %></a>
                  </div>
                </div>
                <p><%= comment.content %></p>
              </div>
              <% reply_comments(comment.id).each do |reply_comment| %>
                <div class="reply_comment_item reply" data="<%= comment.id %>">
                  <div class="media">
                    <div class="d-flex">
                      <%= image_tag reply_comment.user.avatar.url %>
                    </div>
                    <div class="media-body">
                      <h4><%= reply_comment.user.name %></h4>
                      <h5><%= l reply_comment.updated_at, format: :short %></h5>
                      <% if reply_comment.user.id == current_user.id %>
                        <%= link_to t(".delete"), "javascript:void(0)", class: "delete_btn",
                          data_id: reply_comment.id, pid: @product.id, data: { confirm: t(".confirm") } %>
                      <% end %>
                      <a class="reply_btn" parent_id="<%= comment.id %>"
                        user="<%= reply_comment.user.name %>" href="javascript:void(0)"><%= t ".reply" %></a>
                    </div>
                  </div>
                  <p><%= reply_comment.content %></p>
                </div>
              <% end %>
              <% if @reply_comments.any? && @reply_comments.size > 1 %>
                <div class="loadMoreReplyComment" data="<%= comment.id %>">
                  <a href="#"><%= t ".load_reply", count: @reply_comments.size - 1 %></a>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div id="loadMoreComment">
          <a href="#"><%= t ".load_more_comment" %></a>
        </div>
      <% else %>
        <%= t ".not_have_comment"%>
      <% end %>
    </div>
    <div class="col-lg-6">
      <div class="review_box">
        <% if user_signed_in? %>
          <h4><%= t ".post_a_comment"%></h4>
          <form action="javascript:void(0)" class="row contact_form">
            <div class="col-md-12">
              <div class="form-group">
                <textarea pid="<%= @product.id %>" parent_id="" class="form-control"
                  name="comment" id="comment" rows="1" placeholder="<%= t ".comment" %>"></textarea>
              </div>
            </div>
            <div class="col-md-12 text-right">
              <button id="btn-comment" class="btn primary-btn"><%= t ".submit"%></button>
            </div>
          </form>
        <% else %>
          <%= link_to t(".login"), login_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "ajax_comment" %>

app/views/products/_detail_product.html.erb
<!--================Product Description Area =================-->
<section class="product_description_area">
  <div class="container">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
          aria-selected="true"><%= t ".description" %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
					aria-selected="false"><%= t ".comments" %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="review-tab" data-toggle="tab" href="#review" role="tab" aria-controls="review"
					aria-selected="false"><%= t ".reviews" %></a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <p><%= @product.description %></p>
      </div>
      <%= render "comment" %>
      <%= render "review" %>
    </div>
  </div>
</section>
<!--================End Product Description Area =================-->

app/views/products/_left_bar.html.erb
<div class="col-xl-3 col-lg-4 col-md-5">
  <div class="sidebar-categories">
    <div class="head"><%= t ".categories" %></div>
    <ul class="main-categories">
      <% @categories.each do |category| %>
        <% if category.parent_id.nil? %>
          <li class="main-nav-list">
            <div class="row col-lg-12">
              <%= link_to(category.name, shop_path(cat: category.id, sort: params[:sort], rating: params[:rating],
                price_min: params[:price_min], price_max: params[:price_max]), class: "col-md-10 filter-category") %>
              <a class="col-md-2" data-toggle="collapse" href="#cat<%= category.id %>"><i class="arrow fas fa-angle-down"></i></a>
            </div>
            <ul class="collapse" id="cat<%= category.id %>">
              <% sub_categories(category.id).each do |sub_cat| %>
                <li class="main-nav-list child">
                  <%= link_to(sub_cat.name, shop_path(cat: sub_cat.id, sort: params[:sort], rating: params[:rating],
                    price_min: params[:price_min], price_max: params[:price_max]), class: "filter-category") %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="sidebar-filter mt-50">
    <%= form_tag(shop_path, method: :get, id: "click-radio-sort") do %>
      <div class="top-filter-head"><%= t ".product_filters" %></div>
      <div class="common-filter">
        <div class="head"><%= t ".sort" %></div>
        <ul>
          <li class="filter-list"><input class="pixel-radio radio-sort" type="radio" id="sort_a_z" name="sort" value="sort_a_z"><label for="sort_a_z"><%= t ".sort_a_z" %></label></li>
          <li class="filter-list"><input class="pixel-radio radio-sort" type="radio" id="sort_z_a" name="sort" value="sort_z_a"><label for="sort_z_a"><%= t ".sort_z_a" %></label></li>
          <li class="filter-list"><input class="pixel-radio radio-sort" type="radio" id="sort_new" name="sort" value="sort_new"><label for="sort_new"><%= t ".sort_new" %></label></li>
          <li class="filter-list"><input class="pixel-radio radio-sort" type="radio" id="sort_price_a_z" name="sort" value="sort_price_a_z"><label for="sort_price_a_z"><%= t ".sort_price_a_z" %></label></li>
          <li class="filter-list"><input class="pixel-radio radio-sort" type="radio" id="sort_price_z_a" name="sort" value="sort_price_z_a"><label for="sort_price_z_a"><%= t ".sort_price_z_a" %></label></li>
        </ul>
      </div>
      <div class="common-filter">
        <div class="head"><%= t ".rating" %></div>
        <ul>
          <li class="filter-list"><input class="pixel-radio radio-rating" type="radio" id="rating-4" name="rating" value="4">
            <label for="rating-4"><%= t ".bigger" %>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
            </label>
          </li>
          <li class="filter-list"><input class="pixel-radio radio-rating" type="radio" id="rating-3" name="rating" value="3">
            <label for="rating-3"><%= t ".bigger" %>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
            </label>
          </li>
          <li class="filter-list"><input class="pixel-radio radio-rating" type="radio" id="rating-2" name="rating" value="2">
            <label for="rating-2"><%= t ".bigger" %>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
            </label>
          </li>
          <li class="filter-list"><input class="pixel-radio radio-rating" type="radio" id="rating-1" name="rating" value="1">
            <label for="rating-1"><%= t ".bigger" %>
              <i class="fa fa-star"></i>
            </label>
          </li>
        </ul>
      </div>
      <div class="common-filter">
        <div class="head">Price</div>
        <section class="range-slider">
          <span class="rangeValues"></span>
          <input value="<%= params[:price_min] || 0 %>" min="0" max="1000" step="10" type="range" name="price_min" id="price_min">
          <input value="<%= params[:price_max] || 1000 %>" min="0" max="1000" step="100" type="range" name="price_max" id="price_max">
        </section>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "filter" %>

app/views/products/_product.html.erb
<!-- single product -->
<div class="col-lg-4 col-md-6">
  <div class="single-product">
    <% if product.item_photos.first %>
      <% photo_url = product.item_photos.first.photo_url %>
    <% else %>
      <% photo_url = "/assets/fallback/default.jpg" %>
    <% end %>
    <%= link_to product do %>
      <%= image_tag photo_url, class: "img-fluid"  %>
    <% end %>
    <div class="product-details">
      <h6><%= link_to product.name, product %></h6>
      <div class="price">
        <% if product.quantity < 1 %>
          <div>
            <span class="btn-danger"><%= t ".out_stock" %></span>
          </div>
        <% else %>
          <h6><%= number_to_currency price_discounted(product.price, product.discount) %></h6>
          <% if product.discount > 0 %>
            <h6 class="l-through"><%= number_to_currency product.price %></h6>
          <% end %>
        <% end %>
      </div>
      <div>Rating: <%= product.rating %> <i class="fa fa-star"></i></div>
      <div class="prd-bottom">
        <% if product.quantity > 0 %>
          <%= link_to "javascript:void(0)", class: "social-info shopping", data_product_id: product.id do %>
            <span class="fas fa-cart-plus"></span>
            <p class="hover-text"><%= t (".add_to_cart") %></p>
          <% end %>
        <% end %>
        <%= link_to product, class: "social-info" do %>
          <span class="fas fa-info"></span>
          <p class="hover-text"><%= t ".view_more" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_recently_viewed.html.erb
<% if user_signed_in? %>
  <% if current_user.history_views.any? %>
    <% current_user.history_views.each do |h| %>
      <div class="col-lg-4 col-md-4 col-sm-6 mb-20">
        <div class="single-related-product d-flex">
          <% if h.item_photos.first %>
            <% photo_url = h.item_photos.first.photo_url %>
          <% else %>
            <% photo_url = "/assets/fallback/default.jpg" %>
          <% end %>
          <a href="#"><%= image_tag photo_url, {class: "img-fluid p_image"}  %></a>
          <div class="desc" id="product-recently">
            <a href="#" class="title"><%= h.name %></a>
            <div class="price">
              <h6><%= number_to_currency price_discounted(h.price, h.discount) %></h6>
              <h6 class="l-through"><%= number_to_currency h.price %></h6>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= t (".no_recently_product") %>
  <% end %>
<% end %>

app/views/products/_review.html.erb
<div class="tab-pane fade" id="review" role="tabpanel" aria-labelledby="review-tab">
  <div class="row">
    <div class="col-lg-6">
      <div class="row total_rate">
        <div class="col-12">
          <div class="box_total d-flex flex-column align-items-center">
            <h5><%= t ".overall" %></h5>
            <% overall @product %>
            <h3><%= @overall.round(1) %></h3>
            <div data="<%= @overall %>" class="rateyo-readonly"></div>
            <h6>(<%= t ".reviews", count: @product.rates.count(:rating) %>)</h6>
          </div>
        </div>
      </div>
      <div class="review_list">
        <% if @reviews.any? %>
          <% @reviews.each do |review| %>
            <div class="review_item">
              <div class="media">
                <div class="d-flex">
                  <%= image_tag review.user.avatar.url %>
                </div>
                <div class="media-body">
                  <h4><%= review.user.name %></h4>
                  <h5><%= l review.updated_at, format: :short %></h5>
                  <% if review.user.id == current_user.id %>
                    <%= link_to t(".delete"), "javascript:void(0)", class: "delete_review_btn",
                        data_id: review.id, pid: @product.id %>
                  <% end %>
                  <% review.rating.times.each do %>
                    <i class="fa fa-star"></i>
                  <% end %>
                  <p><%= review.content %></p>
                </div>
              </div>
            </div>
          <% end %>
          <div id="loadMore">
            <a href="#"><%= t ".load_more" %></a>
          </div>
        <% else %>
          <%= t ".not_have_review"%>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <% if user_signed_in? %>
        <div class="review_box">
          <h4><%= t ".add_review" %></h4>
          <div class="col-md-12 d-flex align-items-center">
            <p><%= t ".your_rating" %>:</p>
            <div pid="<%= @product.id %>" class="rateyo"></div>
          </div>
          <form action="javascript:void(0)" class="row contact_form">
            <div class="col-md-12">
              <div class="form-group">
                <textarea class="form-control" name="content" id="content" rows="1"
                  placeholder="<%= t ".review" %>"></textarea>
              </div>
              <div class="col-md-12 text-right">
                <button id="rate" class="primary-btn"><%= t "submit" %></button>
              </div>
            </div>
          </form>
          <div class="css-script-clear"></div>
        </div>
      <% else %>
        <%= link_to t(".login"), login_path %>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag "ajax_rating" %>

app/views/products/index.html.erb
<% provide :title, t(".title") %>
<div class="container">
  <div class="row">
    <%= render "left_bar" %>
    <div class="col-xl-9 col-lg-8 col-md-7">
      <div class="filter-bar d-flex flex-wrap align-items-center">
        <%= paginate @products %>
      </div>
      <!-- Start Best Seller -->
      <section class="lattest-product-area pb-40 category-list">
        <div class="row">
          <%= render @products %>
        </div>
      </section>
      <!-- End Best Seller -->
      <div class="filter-bar d-flex flex-wrap align-items-center">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/recently_viewed" %>
<%= javascript_include_tag "ajax_cart" %>

app/views/products/show.html.erb
<% provide :title, t(".title") %>
<!--================Single Product Area =================-->
<div class="product_image_area">
  <div class="container">
    <div class="row s_product_inner">
      <div class="col-lg-6">
        <div class="s_Product_carousel">
          <% @product.item_photos.each do |p| %>
            <div class="single-prd-item">
              <%= image_tag p.photo_url, class: "img-fluid" %>
            </div>
          <% end %>
          <div class="single-prd-item">
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <div class="s_product_text">
          <h3><%= @product.name%></h3>
          <div class="price">
            <h3>
              <%= number_to_currency price_discounted(@product.price, @product.discount) %>
            </h3>
            <% if @product.discount > 0 %>
              <h5 class="l-through"><%= number_to_currency @product.price %></h5>
            <% end %>
          </div>
          <ul class="list">
            <li>
              <span><%= t ".category" %>:</span><%= @product.category.name %>
            </li>
            <% if @product.quantity > 0 %>
              <li>
                <span><%= t ".availibility" %>:</span><%= t ".in_stock" %>
              </li>
            <% else %>
              <li>
                <span><%= t ".availibility" %>:</span><%= t ".out_stock" %>
              </li>
            <% end %>
          </ul>
          <p></p>
          <div class="product_count">
            <label for="qty"><%= t ".quantity" %>:</label>
            <input type="number" class="input-text qty"
              value="1" min="1" max="<%= @product.quantity %>">
          </div>
          <div class="card_area d-flex align-items-center">
            <% if !@product.quantity.zero? %>
              <%= link_to t(".add"), "javascript:void(0)", class: "primary-btn shopping", data_product_id: @product.id %>
            <% end %>
            <div class="fb-share-button" data-href="#" data-layout="button_count" data-size="large">
              <a target="_blank"
              href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
              class="fb-xfbml-parse-ignore">Chia sẻ</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--================End Single Product Area =================-->
  <%= render partial: "detail_product", object: @product %>
  <%= render "shared/recently_viewed" %>
  <%= javascript_include_tag "ajax_cart" %>